import friedChicken from '../../assets/fried_chicken.jpg'

export const menuItems = [
    {
        id: 1,
        name: "Frango Clássico LPH",
        category: "Pratos Principais",
        price: 32.90,
        desc: "4 pedaços de frango frito crocante com tempero secreto, acompanha pão de milho e coleslaw.",
        tags: ["Popular", "Picante"],
        stars: 5,
        img: friedChicken,
    },
    {
        id: 2,
        name: "Combo Família",
        category: "Combos",
        price: 89.90,
        desc: "8 pedaços de frango, 2 acompanhamentos grandes, 4 biscuits e 4 bebidas.",
        tags: ["Melhor Valor"],
        stars: 5,
        img: friedChicken,
    },
    {
        id: 3,
        name: "Bucket Hermanos",
        category: "Combos",
        price: 119.90,
        desc: "12 pedaços variados, 3 acompanhamentos e 6 bebidas. Para toda a família!",
        tags: ["Novo"],
        stars: 4,
        img: friedChicken,
    },
    {
        id: 4,
        name: "Frango Apimentado",
        category: "Pratos Principais",
        price: 29.90,
        desc: "Nossa versão extra picante, marinada em pimenta chipotle por 48h. Para os corajosos!",
        tags: ["Picante", "Popular"],
        stars: 5,
        img: friedChicken,
    },
    {
        id: 5,
        name: "Coleslaw Caseiro",
        category: "Acompanhamentos",
        price: 12.90,
        desc: "Salada cremosa de repolho com molho especial da casa. Acompanhamento perfeito.",
        tags: ["Vegetariano"],
        stars: 4,
        img: friedChicken,
    },
    {
        id: 6,
        name: "Purê Especial",
        category: "Acompanhamentos",
        price: 14.90,
        desc: "Purê de batata cremoso com manteiga e ervas frescas. Reconfortante e delicioso.",
        tags: ["Vegetariano"],
        stars: 4,
        img: friedChicken,
    },
    {
        id: 7,
        name: "Limonada da Casa",
        category: "Bebidas",
        price: 9.90,
        desc: "Limonada fresquinha, feita na hora. Doce, ácida e refrescante.",
        tags: ["Refrescante"],
        stars: 5,
        img: friedChicken,
    },
    {
        id: 8,
        name: "Chá Gelado Southwestern",
        category: "Bebidas",
        price: 9.90,
        desc: "Chá preto gelado com hortelã e um toque de mel. Inspirado no deserto do Novo México.",
        tags: ["Refrescante"],
        stars: 4,
        img: friedChicken,
    },
];

export const categories = ["Todos", "Pratos Principais", "Combos", "Acompanhamentos", "Bebidas"];

export const tagColors = {
    Popular: "bg-blue-900 text-white",
    Picante: "bg-red-500 text-white",
    "Melhor Valor": "bg-yellow-400 text-blue-900",
    Novo: "bg-green-600 text-white",
    Vegetariano: "bg-emerald-100 text-emerald-700",
    Refrescante: "bg-cyan-100 text-cyan-700",
};
